= tz: Time Zone CLI app

Show time zones based on user defined groups.
The group members can be team members, family members, cities, etc.

Place your config file in `~/.tz/config`.

.config file
[source, cue]
----
default_group: "work"

group: "work": {
	member: "John": {city: "Palo Alto"}
	member: "Alan": {city: "Toronto"}
	member: "Mike": {city: "Rochester", country_code: "gb"}
	member: "Steve": {time_zone: "Europe/London"}
}

group: "family": {
	member: "Melqui": {city: "Miami"}
	member: "David": {city: "Calgary"}
	member: "Todos": {city: "San Jose", country_code: "CR"}
	member: "Colombia": {city: "Bogota"}
}
----

Run `tz` to see the time zones of your team members.

----
$ tz
🕙 22:55   @John (PDT)
  18    19    20    21  22  23    00    01    02    03    04    05    06    07    08    09    10    11    12    13    14    15    16    17

🕐 01:55   @Alan (EDT)
  21    22    23    00  01  02    03    04    05    06    07    08    09    10    11    12    13    14    15    16    17    18    19    20

🕕 06:55   @Mike (BST)  @Steve (BST)
  02    03    04    05  06  07    08    09    10    11    12    13    14    15    16    17    18    19    20    21    22    23    00    01
----

Use `tz -s` to see a short version:

----
🕙 22:56   @John (PDT)
🕐 01:56   @Alan (EDT)
🕕 06:56   @Mike (BST)  @Steve (BST)
----

== Finding the time zone for a city

Run: `tz cities <city>` to find the time zone for a city.
Narrow down results using the `-cc` flag.

----
$ tz cities rochester
 Rochester                                GB  Europe/London
 Rochester                                US  America/Chicago
 Rochester                                US  America/New_York
 Rochester Hills                          US  America/Detroit

$ tz cities rochester -cc gb
 Rochester                                GB  Europe/London
----

== Features

* Show the time zone of your team members.

* Use a config file to configure your time zones.

* List all time zones so you can easily edit your config file.

== Motivation

Replacement for my `date` based https://github.com/DavidGamba/bin/blob/96468fe1ebfdc81972dad0b56a11b8023f3f639b/tz[tz] script.

== City time zone information

Information obtained by going to http://download.geonames.org/export/dump/ and downloading the `cities15000.zip` file.

Then a sqlite3 db is generated using the command:

----
sqlite3 cities.db < db.schema
----

Finally, the following query is used to generate an export:

----
sqlite3 cities.db ".headers off" ".mode tabs" "select distinct asciiname,countrycode,timezone from cities15000;"  > cities15000-tz.tsv
----

The TSV is bundled in the binary (The resulting TSV is smaller than its CSV and JSON counterparts).

== LICENSE

This file is part of tz.

Copyright (C) 2023  David Gamba Rios

This Source Code Form is subject to the terms of the Mozilla Public
License, v. 2.0. If a copy of the MPL was not distributed with this
file, You can obtain one at http://mozilla.org/MPL/2.0/.
